int num1 = 150;
int num2 = 3;
int suma = num1 + num2;
println("El resultado de la suma es " + suma);
int resta = num1 - num2;
println ("El resultado de la resta es " + resta);
int multiplicacion = num1 * num2;
println ("El resultado de la multiplicacion es " + multiplicacion);
int division = num1 / num2;
println("El resultado de la division es " + division);
